[View in Colaboratory](https://colab.research.google.com/github/yashgupta1112/assignment/blob/master/assignment_2.ipynb)

In [0]:
import numpy as np
import math

In [0]:
#Question 1
a=np.random.rand(10,1)
print(a)
a.mean()

[[4.99761953e-04]
 [5.70206077e-01]
 [5.00565749e-01]
 [3.02529923e-01]
 [3.08866989e-01]
 [4.85092995e-01]
 [3.93271169e-01]
 [9.69725342e-02]
 [3.87213180e-01]
 [4.81558872e-01]]


0.35267772499299405

In [0]:
#Question 2
b=np.random.rand(20,1)
print(b)
b.var()

[[0.08513393]
 [0.69691907]
 [0.79022437]
 [0.30699004]
 [0.05846213]
 [0.76029862]
 [0.35316964]
 [0.77423737]
 [0.53096409]
 [0.37052182]
 [0.86824741]
 [0.49115172]
 [0.87962958]
 [0.17588094]
 [0.71557601]
 [0.90603529]
 [0.35909871]
 [0.80754202]
 [0.92401172]
 [0.86229993]]


0.07919747997801861

In [0]:
#Question 3
A=np.random.rand(10,20)
print(A)
B=np.random.rand(20,25)
print(B)
C=np.dot(A,B)
print(C)

[[1.47092540e-01 3.54206763e-01 3.61679783e-02 5.93520852e-01
  2.15304577e-01 9.54985822e-01 1.98673327e-01 6.56851287e-01
  7.23128487e-01 8.74605237e-01 4.34996370e-01 9.61042120e-01
  9.14736609e-01 4.37410914e-01 2.49886296e-01 2.81260196e-01
  6.25545111e-02 8.36571034e-01 2.37804701e-01 3.46683724e-01]
 [9.25790910e-01 4.31950305e-01 6.01247092e-01 9.93955149e-01
  4.40574090e-01 9.64685138e-01 8.47082546e-01 6.84287480e-01
  9.43942279e-02 4.13180122e-01 3.36076252e-02 8.25283120e-01
  1.08999417e-01 9.04498257e-01 3.24525894e-01 6.49118030e-01
  4.07775396e-02 8.19529309e-01 4.06471583e-01 9.67410523e-01]
 [3.81606701e-01 6.96364526e-01 2.41910709e-02 9.09837329e-01
  6.29561804e-01 5.08742578e-01 1.86104306e-01 5.14663633e-01
  2.65630656e-01 3.74907476e-01 2.34121866e-01 3.91552120e-01
  5.84956392e-01 7.94444756e-01 7.15232736e-01 2.50480208e-01
  6.74911848e-01 9.42196196e-01 8.13324991e-01 9.36679634e-01]
 [8.70739146e-01 2.96322685e-01 1.95073231e-01 1.30513681e-01
  8.7

In [0]:
#QuesrtiOn 4
b=np.arange(10).reshape(10,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [0]:
def f(x):
  return 1 / (1 + math.exp(-x))
np.apply_along_axis(f,1,b)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])