In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import metrics

In [4]:
data=pd.read_csv("spam.csv",encoding='latin-1')
data.head()

class                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
x=pd.DataFrame(data['SMS'])
x.head()

SMS
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [6]:
y=pd.DataFrame(data['class'])
y.head()

class
0   ham
1   ham
2  spam
3   ham
4   ham

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
tf=data['SMS'].copy()
vectorize=TfidfVectorizer()

In [9]:
features=vectorize.fit_transform(tf)

In [10]:
print(features)

  (0, 3550)	0.1481298737377147
  (0, 8030)	0.22998520738984352
  (0, 4350)	0.3264252905795869
  (0, 5920)	0.2553151503985779
  (0, 2327)	0.25279391746019725
  (0, 1303)	0.24415547176756056
  (0, 5537)	0.15618023117358304
  (0, 4087)	0.10720385321563428
  (0, 1751)	0.2757654045621182
  (0, 3634)	0.1803175103691124
  (0, 8489)	0.22080132794235655
  (0, 4476)	0.2757654045621182
  (0, 1749)	0.3116082237740733
  (0, 2048)	0.2757654045621182
  (0, 7645)	0.15566431601878158
  (0, 3594)	0.15318864840197105
  (0, 1069)	0.3264252905795869
  (0, 8267)	0.18238655630689804
  (1, 5504)	0.27211951321382544
  (1, 4512)	0.4082988561907181
  (1, 4318)	0.5236458071582338
  (1, 8392)	0.4316010362639011
  (1, 5533)	0.5465881710238072
  (2, 4087)	0.07917128722158312
  (2, 3358)	0.11301399735581102
  :	:
  (5570, 4218)	0.12246610191126918
  (5570, 8313)	0.18723687600522523
  (5570, 1084)	0.11225268140936363
  (5570, 4615)	0.1596552981734164
  (5570, 7039)	0.18426763178390446
  (5570, 3308)	0.1217217261863451

In [11]:
type(features)

scipy.sparse.csr.csr_matrix

In [12]:
features.shape

(5572, 8672)

In [13]:
from sklearn.model_selection import StratifiedShuffleSplit

In [14]:
s=StratifiedShuffleSplit(n_splits=2, test_size=0.3, random_state=10)
s.get_n_splits(features,y)
y=y.values.reshape(5572)

In [15]:
for train_index, test_index in s.split(features, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 329 1392 3216 ...  829 4147 5452] TEST: [4035  967 3306 ... 5142 3541  362]
TRAIN: [3053 4819 1146 ... 5505 4447 5245] TEST: [ 172 4794  370 ... 3819 1948 1335]


# KNN

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model1=KNeighborsClassifier(n_neighbors=25)
model1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=25, p=2,
           weights='uniform')

In [18]:
pred=model1.predict(x_test)

In [19]:
metrics.accuracy_score(y_test,pred)

0.9515550239234449

# Naive Bayes

In [20]:
from sklearn.naive_bayes import GaussianNB

In [21]:
model2=GaussianNB()
model2.fit(x_train.todense(),y_train)

GaussianNB(priors=None)

In [22]:
pred2=model2.predict(x_test.todense())

In [23]:
metrics.accuracy_score(y_test,pred2)

0.9055023923444976

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
model3=MultinomialNB()

In [26]:
model3.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [27]:
pred3=model3.predict(x_test)

In [28]:
metrics.accuracy_score(y_test,pred3)

0.9551435406698564

# TREES

In [29]:
from sklearn.tree import DecisionTreeClassifier
model4=DecisionTreeClassifier(criterion='entropy',max_depth=10,random_state=1)
model4.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')

In [30]:
pred4=model4.predict(x_test)

In [31]:
metrics.accuracy_score(y_test,pred4)

0.9688995215311005

In [32]:
from sklearn.ensemble import RandomForestClassifier
model5=RandomForestClassifier(criterion='entropy')
model5.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
pred5=model5.predict(x_test)

In [34]:
metrics.accuracy_score(y_test,pred5)

0.9665071770334929

# SVM

In [35]:
from sklearn.svm import SVC

In [36]:
model6=SVC(gamma=1)
model6.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
pred6=model6.predict(x_test)

In [38]:
metrics.accuracy_score(y_test,pred6)

0.9754784688995215

# Classification Report

In [39]:
from sklearn.metrics import classification_report
print(metrics.classification_report(y_test,pred))

             precision    recall  f1-score   support

        ham       0.95      1.00      0.97      1448
       spam       0.99      0.65      0.78       224

avg / total       0.95      0.95      0.95      1672



In [40]:
print(metrics.classification_report(y_test,pred2))

             precision    recall  f1-score   support

        ham       0.98      0.91      0.94      1448
       spam       0.60      0.89      0.72       224

avg / total       0.93      0.91      0.91      1672



In [41]:
print(metrics.classification_report(y_test,pred3))

             precision    recall  f1-score   support

        ham       0.95      1.00      0.97      1448
       spam       1.00      0.67      0.80       224

avg / total       0.96      0.96      0.95      1672



In [42]:
print(metrics.classification_report(y_test,pred4))

             precision    recall  f1-score   support

        ham       0.97      1.00      0.98      1448
       spam       0.96      0.80      0.87       224

avg / total       0.97      0.97      0.97      1672



In [43]:
print(metrics.classification_report(y_test,pred5))

             precision    recall  f1-score   support

        ham       0.96      1.00      0.98      1448
       spam       0.99      0.75      0.86       224

avg / total       0.97      0.97      0.96      1672



In [44]:
print(metrics.classification_report(y_test,pred6))

             precision    recall  f1-score   support

        ham       0.97      1.00      0.99      1448
       spam       1.00      0.82      0.90       224

avg / total       0.98      0.98      0.97      1672



# Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[1446    2]
 [  79  145]]


In [46]:
print(confusion_matrix(y_test,pred2))

[[1314  134]
 [  24  200]]


In [47]:
print(confusion_matrix(y_test,pred3))

[[1448    0]
 [  75  149]]


In [48]:
print(confusion_matrix(y_test,pred4))

[[1441    7]
 [  45  179]]


In [49]:
print(confusion_matrix(y_test,pred5))

[[1447    1]
 [  55  169]]


In [50]:
print(confusion_matrix(y_test,pred6))

[[1448    0]
 [  41  183]]


In [51]:
filename='SVM.sav'

In [52]:
import pickle

In [53]:
model6


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
pickle.dump(model6, open(filename, 'wb'))

In [55]:
x_test

<1672x8672 sparse matrix of type '<class 'numpy.float64'>'
	with 22172 stored elements in Compressed Sparse Row format>

In [56]:
loaded_model = pickle.load(open(filename, 'rb'))

In [57]:
x=data.iloc[2,1:2]
x

SMS    Free entry in 2 a wkly comp to win FA Cup fina...
Name: 2, dtype: object

In [58]:
x.SMS

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [59]:
tf2=x.SMS
vectorize=TfidfVectorizer()
features2=vectorize.fit_transform(data.iloc[2,1:2])

In [60]:
loaded_model.predict(x_train)

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [61]:
features2.shape

(1, 23)

In [62]:
x_test.shape

(1672, 8672)

In [63]:
x_train.shape

(3900, 8672)

In [64]:
print(features2)

  (0, 10)	0.1643989873053573
  (0, 7)	0.3287979746107146
  (0, 11)	0.1643989873053573
  (0, 22)	0.1643989873053573
  (0, 5)	0.1643989873053573
  (0, 19)	0.4931969619160719
  (0, 21)	0.1643989873053573
  (0, 8)	0.3287979746107146
  (0, 6)	0.1643989873053573
  (0, 9)	0.1643989873053573
  (0, 18)	0.1643989873053573
  (0, 2)	0.1643989873053573
  (0, 12)	0.1643989873053573
  (0, 1)	0.1643989873053573
  (0, 17)	0.1643989873053573
  (0, 3)	0.1643989873053573
  (0, 15)	0.1643989873053573
  (0, 13)	0.1643989873053573
  (0, 16)	0.1643989873053573
  (0, 20)	0.1643989873053573
  (0, 14)	0.1643989873053573
  (0, 4)	0.1643989873053573
  (0, 0)	0.1643989873053573


In [68]:
result = loaded_model.predict(x_train)
print(result)

['ham' 'spam' 'ham' ... 'ham' 'ham' 'ham']


In [66]:
x_train.shape

(3900, 8672)

In [67]:
x_train

<3900x8672 sparse matrix of type '<class 'numpy.float64'>'
	with 51744 stored elements in Compressed Sparse Row format>